services:
  postgres-patient:
    image: postgres:16
    container_name: clinicalflow-patient-db
    environment:
      POSTGRES_USER: clinicalflow
      POSTGRES_PASSWORD: clinicalflow
      POSTGRES_DB: patient_db
    ports:
      - "5432:5432"
    volumes:
      - patient_pgdata:/var/lib/postgresql/data

  postgres-lab:
    image: postgres:16
    container_name: clinicalflow-lab-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lab_db
    ports:
      - "5433:5432"
    volumes:
      - lab_pgdata:/var/lib/postgresql/data

  kafka:
    image: apache/kafka:3.7.1
    container_name: clinicalflow-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

volumes:
  patient_pgdata:
  lab_pgdata: